
CREATE DATABASE gameshop;

USE gameshop;

CREATE TABLE IF NOT EXISTS products (
productId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
productName VARCHAR(100) NOT NULL,
productImg VARCHAR(200)NOT NULL,
productPrice DECIMAL(5,2)NOT NULL,
productCategory VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
userId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userName VARCHAR(100) NOT NULL,
password VARCHAR(200)NOT NULL,
userFirstName VARCHAR(100)NOT NULL,
userLastName VARCHAR(100) NOT NULL,
userMiddleName VARCHAR(100) NOT NULL,
userSuffix VARCHAR(5) NOT NULL
);
