
CREATE DATABASE gameshop;

USE gameshop;

CREATE TABLE IF NOT EXISTS products (
productId INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
productName VARCHAR(100) NOT NULL,
productImg VARCHAR(200)NOT NULL,
productPrice DECIMAL(19,2)NOT NULL,
productCategory VARCHAR(100) NOT NULL,
productDescription TEXT(3000) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
userId INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userName VARCHAR(100) NOT NULL,
password VARCHAR(200)NOT NULL,
userFirstName VARCHAR(100)NOT NULL,
userLastName VARCHAR(100) NOT NULL,
userMiddleName VARCHAR(100) NOT NULL,
userSuffix VARCHAR(5) NOT NULL,
userAddress VARCHAR(200) NOT NULL
);
